# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: transportSystem
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: MTc3ZDg3YTYwMDg2NDBjZDg3YjA2YTBmMGVkNzE2YWM2NmVkNWRlOTc0NzFkODY1YWY5NWZkZjQwOGU4ZjJkN2Q1MTVjZjg4MzU1YWE2MjEwNDA4MmZlOTRkMWU2YzM5YzJhNTk2NTQyNThlYmQ3MjEzZWM3ZmY0YTM2NGQxNTI=
