package com.transport.system.domain;

import static com.transport.system.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class RouteStopAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteStopAllPropertiesEquals(RouteStop expected, RouteStop actual) {
        assertRouteStopAutoGeneratedPropertiesEquals(expected, actual);
        assertRouteStopAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteStopAllUpdatablePropertiesEquals(RouteStop expected, RouteStop actual) {
        assertRouteStopUpdatableFieldsEquals(expected, actual);
        assertRouteStopUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteStopAutoGeneratedPropertiesEquals(RouteStop expected, RouteStop actual) {
        assertThat(actual)
            .as("Verify RouteStop auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteStopUpdatableFieldsEquals(RouteStop expected, RouteStop actual) {
        assertThat(actual)
            .as("Verify RouteStop relevant properties")
            .satisfies(a -> assertThat(a.getStopOrder()).as("check stopOrder").isEqualTo(expected.getStopOrder()))
            .satisfies(a ->
                assertThat(a.getDistanceFromPrev())
                    .as("check distanceFromPrev")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getDistanceFromPrev())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteStopUpdatableRelationshipsEquals(RouteStop expected, RouteStop actual) {
        assertThat(actual)
            .as("Verify RouteStop relationships")
            .satisfies(a -> assertThat(a.getRoute()).as("check route").isEqualTo(expected.getRoute()))
            .satisfies(a -> assertThat(a.getStop()).as("check stop").isEqualTo(expected.getStop()));
    }
}
