package com.transport.system.domain;

import static com.transport.system.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class RouteAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteAllPropertiesEquals(Route expected, Route actual) {
        assertRouteAutoGeneratedPropertiesEquals(expected, actual);
        assertRouteAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteAllUpdatablePropertiesEquals(Route expected, Route actual) {
        assertRouteUpdatableFieldsEquals(expected, actual);
        assertRouteUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteAutoGeneratedPropertiesEquals(Route expected, Route actual) {
        assertThat(actual)
            .as("Verify Route auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteUpdatableFieldsEquals(Route expected, Route actual) {
        assertThat(actual)
            .as("Verify Route relevant properties")
            .satisfies(a -> assertThat(a.getRouteNumber()).as("check routeNumber").isEqualTo(expected.getRouteNumber()))
            .satisfies(a -> assertThat(a.getRouteName()).as("check routeName").isEqualTo(expected.getRouteName()))
            .satisfies(a ->
                assertThat(a.getLength()).as("check length").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLength())
            )
            .satisfies(a -> assertThat(a.getRouteType()).as("check routeType").isEqualTo(expected.getRouteType()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRouteUpdatableRelationshipsEquals(Route expected, Route actual) {
        // empty method
    }
}
