package com.transport.system.domain;

import static com.transport.system.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class StopAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStopAllPropertiesEquals(Stop expected, Stop actual) {
        assertStopAutoGeneratedPropertiesEquals(expected, actual);
        assertStopAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStopAllUpdatablePropertiesEquals(Stop expected, Stop actual) {
        assertStopUpdatableFieldsEquals(expected, actual);
        assertStopUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStopAutoGeneratedPropertiesEquals(Stop expected, Stop actual) {
        assertThat(actual)
            .as("Verify Stop auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStopUpdatableFieldsEquals(Stop expected, Stop actual) {
        assertThat(actual)
            .as("Verify Stop relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a ->
                assertThat(a.getLatitude()).as("check latitude").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLatitude())
            )
            .satisfies(a ->
                assertThat(a.getLongitude()).as("check longitude").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getLongitude())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStopUpdatableRelationshipsEquals(Stop expected, Stop actual) {
        // empty method
    }
}
