package com.transport.system.domain;

import static com.transport.system.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class WaybillAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaybillAllPropertiesEquals(Waybill expected, Waybill actual) {
        assertWaybillAutoGeneratedPropertiesEquals(expected, actual);
        assertWaybillAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaybillAllUpdatablePropertiesEquals(Waybill expected, Waybill actual) {
        assertWaybillUpdatableFieldsEquals(expected, actual);
        assertWaybillUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaybillAutoGeneratedPropertiesEquals(Waybill expected, Waybill actual) {
        assertThat(actual)
            .as("Verify Waybill auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaybillUpdatableFieldsEquals(Waybill expected, Waybill actual) {
        assertThat(actual)
            .as("Verify Waybill relevant properties")
            .satisfies(a -> assertThat(a.getDocumentNumber()).as("check documentNumber").isEqualTo(expected.getDocumentNumber()))
            .satisfies(a -> assertThat(a.getActualDeparture()).as("check actualDeparture").isEqualTo(expected.getActualDeparture()))
            .satisfies(a -> assertThat(a.getActualReturn()).as("check actualReturn").isEqualTo(expected.getActualReturn()))
            .satisfies(a ->
                assertThat(a.getMileageStart())
                    .as("check mileageStart")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMileageStart())
            )
            .satisfies(a ->
                assertThat(a.getMileageEnd())
                    .as("check mileageEnd")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getMileageEnd())
            )
            .satisfies(a ->
                assertThat(a.getFuelConsumptionPlan())
                    .as("check fuelConsumptionPlan")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFuelConsumptionPlan())
            )
            .satisfies(a ->
                assertThat(a.getFuelConsumptionFact())
                    .as("check fuelConsumptionFact")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getFuelConsumptionFact())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWaybillUpdatableRelationshipsEquals(Waybill expected, Waybill actual) {
        // empty method
    }
}
